[package]
name = "about-me"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["backend", "frontend"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.158", features = ["serde_derive"] }
